version: '3.8'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ROOT_URL=http://localhost:4000
    ports:
      - 4000:3000
    depends_on:
      - mongo
    networks:
      - rocketchat-network

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - ./data/db:/data/db
    networks:
      - rocketchat-network

networks:
  rocketchat-network:
    driver: bridge